#version: "3.7"
#services:
#  app:
#    container_name: 'backend'
#    build:
#      context: .
#    env_file:
#      - .env
#    restart: on-failure
#    volumes:
#      - ./server:/app
#      - /app/node_modules
#    command: >
#      /wait-for-it.sh db:5432 -- npm start
#  db:
#    image: postgres:12.11-alpine
#    container_name: 'postgres'
#    ports:
#      - "5432:5432"
##    environment:
##      POSTGRES_DB: project_node
##      POSTGRES_USER: postgres
##      POSTGRES_PASSWORD: root
##      POSTGRES_HOST: localhost
#    env_file:
#      - .env.-db
#    restart: always
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
##volumes:
##  db:
##    driver: local
#
#  web:
#    image: nginx:alpine
#    container_name: 'frontend'
#    ports:
#      - "80:3000"
#    restart: on-failure
#    volumes:
#      - ./client:/usr/share/nginx/html
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#version: '3.7'
#services:
#  db:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
#  api:
#    container_name: quotes-api
#    build:
#      context: ./
#      target: production
#    image: quotes-api
#    depends_on:
#      - db
#    ports:
#      - 5500:5500
#    environment:
#      NODE_ENV: production
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: postgres
#    links:
#      - db
#    volumes:
#      - './:/src'
#volumes:
#  db:
#    driver: local
version: "3.7"
services:
  server:
    container_name: "server"
    env_file:
      - .env
    build: ./server/
    ports:
      - "5500:5500"
  pg:
    image: "postgres:12.11-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_DB: project_node
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: localhost
#    env_file:
#      - .env.-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  client:
    container_name: "client"
    build: ./client/
    ports:
      - "3000:3000"