version: "3.7"


services:
  app:
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./server:/app
      - /app/node_modules
    command: >
      /wait-for-it.sh db:5432 -- npm start
  db:
    image: postgres:12.11
    ports:
      - "5433:5432"
#    environment:
#      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - PGDATA=/var/lib/postgresql/data/db
    env_file:
      - .env.-db
    restart: on-failure
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  web:
    image: nginx:alpine
    ports:
      - "80:3000"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
